spring.application.name=planner

spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=auth
spring.datasource.password=${DB_PASSWORD:auf67}

spring.jpa.hibernate.ddl-auto=validate
